#!/usr/bin/env sh

[ -f ~/.zshrc ] && profile_name=.zshrc
[ ! "$profile_name" ] && [[ -f ~/.bashrc ]] && profile_name=.bashrc

[ "$(echo $PATH | grep -o  'node_modules/.bin')" ] && echo "skip no-npm installation" || echo 'export PATH=./node_modules/.bin:$PATH' > ~/$profile_name
